application: plysql
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index.py

- url: /what-is-plysql
  script: what-is-plysql.py

- url: /img
  static_dir: img

- url: /(.*?)
  script: /\1
